### ISSUE TITLE
New Maintainer Application For Redmi 12 5G / Poco M6 Pro 5G (Sky)

### ISSUE THREAD

**Issue by suvojit213** [Project-Awaken/official_devices#126]
## Device you want to apply for
```
Redmi 12 5G / Poco M6 Pro 5G (sky)
```

## Device tree sources

```
https://github.com/suvojit213/device_xiaomi_sky.git
https://github.com/suvojit213/device_xiaomi_sky-kernel.git
https://github.com/suvojit213/vendor_xiaomi_sky.git
```

## Link to the platform where you have released your unofficial build
```
https://t.me/Redmi125GChannel/403
```

## Other ROM's you maintain officially or unofficially
```
Voltage OS , Superior OS
```

## Bugs on unofficial build
```
No Bugs Stable build
```

## How long have you been building for?
```
2Months
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
Yes. Because not have proper kernel source, kernel source is broken
```

### Your Telegram username
```
suvojeet_sengupta
```

**Comment by arnavpuranik** [comment]
Well you were rejected anyways since we already have a maintainer for your device. But regardless, I did look at your trees.

1. [What even? ](https://github.com/suvojit213/device_xiaomi_sky/commit/43aadc691267e68cf0689aaf9f37d6765a64ad3c) There's a thing called git rebase. LEARN.
2. [This Commit](https://github.com/suvojit213/device_xiaomi_sky/commit/0178c09b55e5faba1ea8b460f2964b51f3d2569d) isn't in the right format. 
3. [Unnecessary flag. ](https://github.com/suvojit213/device_xiaomi_sky/blob/0178c09b55e5faba1ea8b460f2964b51f3d2569d/awaken_sky.mk#L28)
4. [Lineage Overlays](https://github.com/suvojit213/device_xiaomi_sky/tree/awakenos/overlay-lineage) in Awaken tree?
5. Ideally [this](https://github.com/suvojit213/device_xiaomi_sky/commit/f5d74d90d1e07b31e112a522d3f6bd497b7f1136) should've been squashed in some other commit. 
6. As per [this](https://github.com/suvojit213/device_xiaomi_sky/commit/e067a320bb254d6d9da6cf2086788d70baf8ec32) and considering your git skills, I highly doubt you did NOT do [this](https://github.com/suvojit213/vendor_xiaomi_sky/commit/a3626e17d3e9143203da1d9b0b155d60ba7a4812) and probably even [this](https://github.com/suvojit213/vendor_xiaomi_sky/commit/0d751161200b3c8df6caf3a258c99fa3b4d34af5) yourself. Please Provide an explaination, else give credit to the right author, since this might be a kang. We have a strict no kang policy. 


You are rejected.

**Comment by suvojit213** [comment]
Yes I am learner , Thanks for giving me such suggestions it's really help me to learn more 
Thank you ❣️

**Comment by suvojit213** [comment]
I have done all changes please look into this ❣️❣️

**Comment by arnavpuranik** [comment]
Still we already have a maintainer for your device, we can't take you.
