### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by bntxperses** [Project-Awaken/official_devices#61]
## Device you want to apply for
```
Realme X3 (RMX2081)
```
## Device tree sources

```
https://github.com/bntxperses/device_realme_x3.git
https://github.com/bntxperses/android_kernel_realme_x3.git
https://github.com/bntxperses/android_vendor_realme_x3.git
```

## Link to the platform where you have released your unofficial build
```
https://forum.xda-developers.com/t/a13-awaken-os-for-realme-x3-x3-superzoom-x3-unofficial.4521047/
```

## Other ROM's you maintain officially or unofficially
```
Evolution X unofficial & Cherish OS Official
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
2 Months
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Permissive 
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@bntxperses
```

**Comment by arnavpuranik** [comment]
Hey there!

I have to reject your maintainership for a few reasons.

1. Your commit titles are misformatted as well as misleading at times too (mentioned below). 
At some places you're using 
device: change

At other's you're using 
device : change

It doesn't look clean and commit history feels like a mess. 

2. Your [Build Fingerprint](https://github.com/bntxperses/device_realme_x3/blob/886304f638b80d2db9e7349e3b9b9312675a8bba/awaken_x3.mk#L56) and [description](https://github.com/bntxperses/device_realme_x3/blob/886304f638b80d2db9e7349e3b9b9312675a8bba/awaken_x3.mk#L60), doesn't match. WHY? 
3. [This ](https://github.com/bntxperses/device_realme_x3/commit/9eca11fe2b74df17bdb6b40ff1f20c7f415235e0) change is kinda useless now because of [this](https://github.com/Cource/hentaios_device_xiaomi_sdm845-common/commit/9291f957d75f6d6d084124bf64c84f3307fa8b04) where reasons are properly mentioned as to why it is useless.
4. Why'd you add [Launcher3 Permissions in your dt?](https://github.com/bntxperses/device_realme_x3/blob/awaken/configs/permissions/privapp-permissions-whitelist-system_ext.xml) 
5. You wrote [don't override build fp](https://github.com/bntxperses/device_realme_x3/commit/c162dafb71c4c98e4f94eabd4f314739a359ea45) and you literally [added override for desc here](https://github.com/bntxperses/device_realme_x3/blob/886304f638b80d2db9e7349e3b9b9312675a8bba/awaken_x3.mk#L60). Again misleading title. 
6. Why do you even need a [config.mk here](https://github.com/bntxperses/device_realme_x3/blob/awaken/GoogleCameraGo/config.mk)? 

I didn't even look at your vendor and kernel trees after this. 
Anyway, considering all these things, you're unfit for maintaining officially, consider re-applying later.
